# Generated by Django 5.1.7 on 2025-06-20 17:53

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text='Nome do documento de origem', max_length=255)),
                ('content', models.TextField(help_text='O pedaço de texto do documento')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
            ],
        ),
    ]
